### PR TITLE
Update action button label from 'Create Rule' to 'Activate Rule'

### PR DESCRIPTION
**Pull request by Precious000**
#Changelog

poetry run towncrier create -c "Create Rule' to 'Activate Rule" 897.changed.md
 

#All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

### Changed

- Update action button label from 'Create Rule' to 'Activate Rule'

### CODE REVIEW

**Comment by Precious000** [comment]
Hi @abompard can you please review what I did, I will appreciate any correction. I'm also meant to wait for you to merge or should I go ahead?

**Comment by abompard** [comment]
There are a lot of unrelated commits, please rebase on the tip on the develop branch.

**Comment by Precious000** [comment]
Just saw it now😭, must have been because I had another project on the same branch, I’ll rebase and force push again. Thank you so much.

**Comment by abompard** [comment]
Thanks for fixing the conflicts. As you can see there are 13 commits in this pull request, ending up in a one-line change. Could you rebase it on the develop branch to leave only your commit? You can try `git rebase -i develop`.

**Pull request closed without merging**
