### PR TITLE
prototype connecting to FASJSON 

### PR DESCRIPTION
**Pull request by ryanlerch**
This adds the basic funtionality of connecting to FASJSON and returning
the information back to the frontend. It also sets up the vagrant setup
for this as well.

Signed-off-by: Ryan Lerch <rlerch@redhat.com>

### CODE REVIEW

**Review by nphilipp — APPROVED** [review]
Looks good to me!

**Comment by nphilipp** [comment]
Fixed import sort order.

**Comment by abompard** [comment]
You need to `dnf install -y krb5-devel` in the github action, I believe.

**Comment by abompard** [comment]
Now that I think of it, we may not be able to use the `fasjson_client` helper, because it's not async. We may have to do the HTTP queries by hand (with HTTPX maybe?)

**Pull request merged**
