### PR TITLE
Few small fixes

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Review by AdamSaleh — APPROVED** [review]
Most of these look as the usual python2 to python3 migration. LGTM

**Comment by AdamSaleh** [comment]
@pypingou or @mattiaverga can you add me to this repo?

**Comment by mattiaverga** [comment]
@AdamSaleh I can't, I'm not and admin anywhere

**Comment by pypingou** [comment]
> @pypingou or @mattiaverga can you add me to this repo?

Done :)

**Pull request merged**
