### PR TITLE
New fmn.rules for the MBS.

### PR DESCRIPTION
**Pull request by ralphbean**
This is for https://pagure.io/fm-orchestrator/issue/406

### CODE REVIEW

**Comment by pypingou** [comment]
Looks fine to me

**Comment by jeremycline** [comment]
Looks fine to me as well. How soon do you need this deployed?

**Comment by ralphbean** [comment]
> Looks fine to me as well. How soon do you need this deployed?

Thanks!  Somewhere between as soon as possible and whenever is convenient.  :)

@contyk is using https://mbs.fedoraproject.org/ now.  If he could receive notifications when his builds were done, that would be useful to him.  It would be very nice to have, but is not mission critical.

FWIW, for this to be useful, it will also need a cut of fedmsg_meta... deployed:  https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/pull/417

**Comment by ralphbean** [comment]
Thanks @jeremycline!

**Pull request merged**
