### PR TITLE
Catch any exception caused by a backend "handle"

### LINKED ISSUE #204: Unhandled exception from a timed out request
There's an unhandled exception in the backend if a request times out and it appears to cause the whole backend to stop doing anything:
```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 368, in callback
self._startRunCallbacks(result)
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
self._runCallbacks()
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1101, in gotResult
_inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1045, in _inlineCallbacks
result = g.send(result)
File "/usr/lib/python2.7/site-packages/fmn/consumer/backend.py", line 216, in read
backend.handle(session, recipient, raw_msg)
File "/usr/lib/python2.7/site-packages/fmn/consumer/backends/mail.py", line 160, in handle
content = fedmsg.meta.msg2long_form(msg, **self.config) or u''
File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 142, in __wrapper
return f(msg, **config)
File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 161, in __wrapper
return f(msg, processor=processor, **config)
File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 247, in msg2long_form
result = processor.long_form(msg, **config)
File "/usr/lib/python2.7/site-packages/fedmsg_meta_fedora_infrastructure/scm.py", line 67, in long_form
response = requests.get(url.format(repo=repo, rev=rev))
File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
return request('get', url, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
response = session.request(method=method, url=url, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 602, in send
history = [resp for resp in gen] if allow_redirects else []
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
allow_redirects=False,
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
```

### PR DESCRIPTION
**Pull request by jeremycline**
fixes #204

Signed-off-by: Jeremy Cline <jeremy@jcline.org>

### CODE REVIEW

**Review by puiterwijk — CHANGES_REQUESTED** [review]
Let's do the same requeueing we do when we try to figure out who is supposed to receive the message. That was that we originally also did for the handle'ing, until that code was moved away.

**Comment by jeremycline** [comment]
``basic_nack`` [requeues by default](https://pika.readthedocs.io/en/0.11.0/modules/channel.html#pika.channel.Channel.basic_nack).

**Comment by puiterwijk** [comment]
Yes, but at the *front* of the queue. Which means that if there's a message that is failing to process for some reason, FMN will get stuck at that message. The explicit requeue was so that it would go to the back of the queue.

**Comment by jeremycline** [comment]
Adjusted.

**Review by puiterwijk — APPROVED** [review]

**Pull request merged**
